"""Storage contracts used by application services; no UI or HTTP types."""
from typing import Protocol

class SettingsStore(Protocol):
    def read(self) -> dict: ...
    def write(self, value: dict) -> None: ...

class HistoryStore(Protocol):
    def read(self) -> list[dict]: ...
    def append(self, entry: dict) -> None: ...

class SecretStore(Protocol):
    def put(self, owner_id: str, provider: str, value: str) -> str: ...
    def get(self, owner_id: str, version: str) -> str: ...

class CacheStore(Protocol):
    def put(self, owner_id: str, account: str, key: str, data) -> None: ...
    def get(self, owner_id: str, account: str, key: str, max_age_hours=24): ...
